name: canvas_example
description: A sample Polymer application
dependencies:
  core_elements: any
  paper_elements: any
  polymer: '>=0.11.0 <0.12.0'
transformers:
- polymer:
    entry_points: web/canvas_example.html
